// <auto-generated />
using System;
using FGORankGenerator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FGORankGenerator.Migrations
{
    [DbContext(typeof(ServantContext))]
    partial class ServantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.27");

            modelBuilder.Entity("FGORankGenerator.Models.Servant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppMediaOrbit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppMediaRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("OverallRank")
                        .HasColumnType("REAL");

                    b.Property<string>("Range")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servants");
                });
#pragma warning restore 612, 618
        }
    }
}
